# 服务器端口，如果不配置默认是8080端口
server:
  port: 9999

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  application:
    name: dubbo-consumer
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: center-zhao-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
# swagger 配置 是否开启
mconfig:
  swagger-ui-open: true
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /sys/user/login
#spring:
#  security:
#    user:
#      name: root
#      password: 123456

fdfs:
  soTimeout: 15000 #socket连接超时时⻓
  connectTimeout: 6000 #连接tracker服务器超时时⻓
  reqHost: 47.113.81.149 #nginx访问地址
  reqPort: 8080 #nginx访问端⼝
  thumb-image: #缩略图⽣成参数，可选
    height: 150
    width: 150
  trackerList: #TrackerList参数,⽀持多个，我这⾥只有⼀个，如果有多个在下⽅加-x.x.x.x:port
    - 47.113.81.149:22122
  web-server-url: http://47.113.81.149:8081/